In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from pandas import DataFrame, read_csv
from ToolBox import CrossValidation
import json

In [2]:
train = pd.read_csv('./train.csv')
keys = ["OutcomeType", "AnimalType", "SexuponOutcome", "AgeuponOutcome", "Breed", "Color"]
train

AnimalID        Name             DateTime      OutcomeType  \
0      A671945     Hambone  2014-02-12 18:22:00  Return_to_owner   
1      A656520       Emily  2013-10-13 12:44:00       Euthanasia   
2      A686464      Pearce  2015-01-31 12:28:00         Adoption   
3      A683430         NaN  2014-07-11 19:09:00         Transfer   
4      A667013         NaN  2013-11-15 12:52:00         Transfer   
5      A677334        Elsa  2014-04-25 13:04:00         Transfer   
6      A699218       Jimmy  2015-03-28 13:11:00         Transfer   
7      A701489         NaN  2015-04-30 17:02:00         Transfer   
8      A671784        Lucy  2014-02-04 17:17:00         Adoption   
9      A677747         NaN  2014-05-03 07:48:00         Adoption   
10     A668402         NaN  2013-12-05 15:50:00         Transfer   
11     A666320         NaN  2013-11-04 14:48:00         Adoption   
12     A684601      Rocket  2016-02-03 11:27:00         Adoption   
13     A704702     Scooter  2015-06-08 16:30:00  Return_to_owner   
14     A688584     Preston  2015-11-25 15:00:00  Return_to_owner   
15     A678825      Oliver  2014-07-12 12:10:00         Adoption   
16     A678050         NaN  2014-05-03 16:15:00         Transfer   
17     A680028         NaN  2014-06-07 12:54:00         Transfer   
18     A679010     Chrissy  2014-05-17 11:32:00         Transfer   
19     A684787        Kuma  2014-07-30 17:34:00  Return_to_owner   
20     A670658      Anders  2014-01-19 15:03:00         Transfer   
21     A708812    Munchkin  2015-09-18 15:19:00         Transfer   
22     A705262     Jamaica  2015-08-15 14:22:00         Adoption   
23     A665781     Quattro  2013-10-28 16:32:00         Adoption   
24     A676333     Trigger  2014-04-09 17:44:00  Return_to_owner   
25     A712750       Olive  2015-10-03 15:44:00         Transfer   
26     A718832         Nia  2016-01-15 17:31:00         Adoption   
27     A698777       Chloe  2015-03-25 18:50:00         Adoption   
28     A715348     Cymbale  2015-11-21 13:01:00         Adoption   
29     A708666         Jax  2015-07-30 14:30:00  Return_to_owner   
...        ...         ...                  ...              ...   
26699  A676460       Mario  2014-04-21 14:01:00       Euthanasia   
26700  A704999        Lion  2015-06-15 19:28:00  Return_to_owner   
26701  A678842        Ella  2014-06-15 17:41:00         Transfer   
26702  A713637         NaN  2015-10-11 09:42:00             Died   
26703  A716670      Mowmow  2015-12-04 12:22:00         Transfer   
26704  A716223       Alice  2015-11-17 17:17:00         Transfer   
26705  A662498       Grace  2013-10-19 15:34:00         Transfer   
26706  A689942        Zoey  2014-10-19 13:29:00         Adoption   
26707  A682690         NaN  2014-07-01 17:06:00       Euthanasia   
26708  A666920      Herbie  2013-11-13 17:32:00         Transfer   
26709  A714386         NaN  2015-10-24 00:00:00         Adoption   
26710  A692622      Bonnie  2014-11-24 17:21:00         Transfer   
26711  A666284       Sonja  2013-10-30 18:32:00         Transfer   
26712  A535277      Merlin  2015-04-20 16:04:00  Return_to_owner   
26713  A671169         NaN  2014-01-20 17:37:00       Euthanasia   
26714  A679031        Pete  2014-05-31 16:11:00         Adoption   
26715  A708833        Luna  2015-08-05 17:03:00         Adoption   
26716  A697158         Max  2015-05-02 21:04:00         Adoption   
26717  A519949       Bella  2014-06-30 17:34:00  Return_to_owner   
26718  A701044         NaN  2015-04-28 14:26:00         Adoption   
26719  A707871         NaN  2015-07-20 09:00:00         Transfer   
26720  A704405     Brownie  2015-07-18 14:08:00         Adoption   
26721  A662019  Green Bean  2014-07-17 09:43:00         Adoption   
26722  A687056         NaN  2014-08-31 09:00:00         Transfer   
26723  A716997        Zeus  2016-01-29 18:52:00         Adoption   
26724  A702446         NaN  2015-05-14 11:56:00         Transfer   
26725  A718934         NaN  2016-01-20 18:59:00         Transf

In [3]:
print "OutcomeType"

dict_temp = {}

dict_temp["OutcomeType"] = np.array([val for val in train.OutcomeType.unique() if str(val) != 'nan'and str(val).lower() != 'unknown'])
dict_temp["OutcomeType"] = np.sort(dict_temp["OutcomeType"]) #To make easier the construction of submission.
dict_temp["OutcomeType"]

OutcomeType


array(['Adoption', 'Died', 'Euthanasia', 'Return_to_owner', 'Transfer'], 
      dtype='|S15')

In [4]:
#print "OutcomeSubtype"

#dict_temp["OutcomeSubtype"] = np.array([val for val in train.OutcomeSubtype.unique() if str(val) != 'nan'and str(val).lower() != 'unknown'])
#dict_temp["OutcomeSubtype"] 

In [5]:
print "Breed"
dict_temp["Breed"] = np.array([val for val in train.Breed.unique() if str(val) != 'nan'and str(val).lower() != 'unknown'])
np.set_printoptions(threshold='nan')
dict_temp["Breed"]

Breed


array(['Shetland Sheepdog Mix', 'Domestic Shorthair Mix', 'Pit Bull Mix',
       'Lhasa Apso/Miniature Poodle', 'Cairn Terrier/Chihuahua Shorthair',
       'American Pit Bull Terrier Mix', 'Cairn Terrier',
       'Miniature Schnauzer Mix', 'Yorkshire Terrier Mix',
       'Great Pyrenees Mix', 'Angora Mix', 'Flat Coat Retriever Mix',
       'Queensland Heeler Mix', 'Plott Hound/Boxer', 'German Shepherd Mix',
       'American Staffordshire Terrier Mix', 'Chihuahua Shorthair Mix',
       'Russian Blue Mix', 'Labrador Retriever Mix',
       'Collie Smooth/German Shepherd', 'Domestic Longhair Mix', 'Beagle',
       'Pit Bull/Labrador Retriever', 'Blue Lacy Mix',
       'Black Mouth Cur Mix', 'Dachshund/Beagle', 'Dachshund Mix',
       'Maltese Mix', 'Pointer Mix', 'English Foxhound', 'Vizsla Mix',
       'German Shepherd/Great Pyrenees',
       'Cardigan Welsh Corgi/Chihuahua Shorthair', 'Domestic Longhair',
       'Chow Chow/Pit Bull', 'Chihuahua Shorthair', 'Siamese Mix',
       'Domestic

In [6]:
print "AnimalType"
dict_temp["AnimalType"] = np.array([val for val in train.AnimalType.unique() if str(val) != 'nan'and str(val).lower() != 'unknown'])
np.set_printoptions(threshold='nan')
dict_temp["AnimalType"]

AnimalType


array(['Dog', 'Cat'], 
      dtype='|S3')

In [7]:
print "SexuponOutcome"
dict_temp["SexuponOutcome"] = np.array([val for val in train.SexuponOutcome.unique() if str(val) != 'nan' and str(val).lower() != 'unknown'])
dict_temp["SexuponOutcome"]

SexuponOutcome


array(['Neutered Male', 'Spayed Female', 'Intact Male', 'Intact Female'], 
      dtype='|S13')

In [8]:
print "AgeuponOutcome"
dict_temp["AgeuponOutcome"] = train.AgeuponOutcome.unique()
dict_temp["AgeuponOutcome"] 

AgeuponOutcome


array(['1 year', '2 years', '3 weeks', '1 month', '5 months', '4 years',
       '3 months', '2 weeks', '2 months', '10 months', '6 months',
       '5 years', '7 years', '3 years', '4 months', '12 years', '9 years',
       '6 years', '1 weeks', '11 years', '4 weeks', '7 months', '8 years',
       '11 months', '4 days', '9 months', '8 months', '15 years',
       '10 years', '1 week', '0 years', '14 years', '3 days', '6 days',
       '5 days', '5 weeks', '2 days', '16 years', '1 day', '13 years', nan,
       '17 years', '18 years', '19 years', '20 years'], dtype=object)

In [9]:
print "Color"
dict_temp["Color"] = np.array([val for val in train.Color.unique() if str(val) != 'nan' and str(val).lower() != 'unknown'])
dict_temp["Color"]

dict_colors = {}

i = 1

for value in dict_temp["Color"]:
    if value not in dict_colors and '/' not in value:
        dict_colors[value] = i
        i+=1
    elif value not in dict_colors and  '/' in value:
        temp_val = value.split('/')
        temp = '{1}/{0}'.format(temp_val[0], temp_val[1]) 
        if temp not in dict_colors:
            dict_colors[value] = i
            i += 1

#print dict_colors
            
def getColorCode(colorValue):
    if colorValue in dict_colors:
        return dict_colors[colorValue]
    splits = colorValue.split('/')
    if len(splits) > 1: #Must be 2
        val = '{1}/{0}'.format(splits[0], splits[1])
        if val in dict_colors:
            return dict_colors[val]
    return 0

Color


In [10]:
dict_colors

{'Agouti': 142,
 'Agouti/Brown Tabby': 239,
 'Apricot': 72,
 'Apricot/Brown': 156,
 'Apricot/White': 57,
 'Black': 11,
 'Black Brindle': 96,
 'Black Brindle/Black': 154,
 'Black Brindle/Brown': 209,
 'Black Brindle/Brown Brindle': 262,
 'Black Brindle/White': 103,
 'Black Smoke': 90,
 'Black Smoke/Brown Tabby': 168,
 'Black Smoke/White': 85,
 'Black Tabby': 101,
 'Black Tabby/Orange': 155,
 'Black Tabby/White': 42,
 'Black Tiger/White': 250,
 'Black/Black': 144,
 'Black/Black Smoke': 165,
 'Black/Black Tabby': 186,
 'Black/Blue Merle': 123,
 'Black/Brown': 19,
 'Black/Brown Brindle': 44,
 'Black/Buff': 98,
 'Black/Gray': 53,
 'Black/Orange': 126,
 'Black/Red': 14,
 'Black/Silver Tabby': 130,
 'Black/Tan': 6,
 'Black/Tricolor': 71,
 'Black/White': 17,
 'Black/Yellow': 241,
 'Black/Yellow Brindle': 202,
 'Blue': 24,
 'Blue Cream': 4,
 'Blue Cream/Blue Tiger': 92,
 'Blue Cream/Buff': 223,
 'Blue Merle': 47,
 'Blue Merle/Blue Merle': 235,
 'Blue Merle/Brown': 105,
 'Blue Merle/Cream': 178,

In [11]:
import math

keys

['OutcomeType',
 'AnimalType',
 'SexuponOutcome',
 'AgeuponOutcome',
 'Breed',
 'Color']

In [12]:
def convertAgeToNum(age):
    if str(age).isdigit():
        return age
    elif str(age) == 'nan':
        return 0
    else:
        age = age.strip()
        age = age.lower()
        splits = age.split()
        if "year" in splits[1]:
            return float(splits[0]) * 365
        elif "month" in splits[1]:
            return float(splits[0]) * 30
        elif "week" in splits[1]:
            return float(splits[0]) * 7
        elif "day" in splits[1]:
            return float(splits[0])

In [13]:
train_transformed = []
for idx, row in train.iterrows():
    lis = []
    for key in keys:
        if key == "AgeuponOutcome":
            age_in_days = convertAgeToNum(row[key])
            lis.append(age_in_days)
        elif key == 'Color':
            if str(row[key]) != "nan" and str(row[key]).lower() != "unknown":
                lis.append(getColorCode(row[key]))
            else:
                lis.append(0)
        elif str(row[key]) != "nan" and str(row[key]).lower() != "unknown":            
            temp = np.where(dict_temp[key] == row[key])[0][0]+1
            lis.append(temp)
        else:
            lis.append(0)
    train_transformed.append(np.array(lis))


In [14]:
train_transformed = np.array(train_transformed, np.int16)
print train_transformed

[[   4    1    1  365    1    1]
 [   3    2    2  365    2    2]
 [   1    1    1  730    3    3]
 [   5    2    3   21    2    4]
 [   5    1    1  730    4    5]
 [   5    1    4   30    5    6]
 [   5    2    3   21    2    7]
 [   5    2    0   21    2    8]
 [   1    1    2  150    6    9]
 [   1    1    2  365    7   10]
 [   5    2    0  730    2   11]
 [   1    1    2  730    8   12]
 [   1    1    1 1460    3   13]
 [   4    1    1  730    9   14]
 [   4    1    1  365   10   15]
 [   1    2    1   90    2   16]
 [   5    2    3   21    2    8]
 [   5    1    4   14    3    1]
 [   5    2    4  730   11   10]
 [   4    1    1  365   12   11]
 [   5    1    3   60   13   17]
 [   5    2    2  365    2   10]
 [   1    1    2  730   14   18]
 [   1    1    1  300   15    1]
 [   4    1    1   60   15   19]
 [   5    2    4   30    2   20]
 [   1    1    2  180   16   21]
 [   1    1    2 1825   17   22]
 [   1    2    2   60    2   23]
 [   4    2    1 2555   18   24]
 [   3    

In [15]:
#Train the model: RandomForest.

labels = [x[0] for x in train_transformed]
train = [x[1:] for x in train_transformed]

In [16]:
test = pd.read_csv('./test.csv')
test_keys = ["AnimalType", "SexuponOutcome", "AgeuponOutcome", "Breed", "Color"]
test

ID        Name             DateTime AnimalType SexuponOutcome  \
0          1      Summer  2015-10-12 12:15:00        Dog  Intact Female   
1          2    Cheyenne  2014-07-26 17:59:00        Dog  Spayed Female   
2          3         Gus  2016-01-13 12:20:00        Cat  Neutered Male   
3          4       Pongo  2013-12-28 18:12:00        Dog    Intact Male   
4          5     Skooter  2015-09-24 17:59:00        Dog  Neutered Male   
5          6        Beau  2015-06-23 11:17:00        Dog  Neutered Male   
6          7        Bobo  2014-03-12 09:45:00        Cat  Neutered Male   
7          8        Abby  2014-06-25 08:27:00        Cat  Spayed Female   
8          9  Ruby Grace  2014-11-12 18:05:00        Dog  Spayed Female   
9         10        Ruby  2014-04-07 17:41:00        Dog  Spayed Female   
10        11      Marlee  2014-01-01 17:03:00        Dog  Spayed Female   
11        12        Lala  2014-09-19 15:40:00        Dog  Intact Female   
12        13       Chloe  2015-01-25 15:13:00        Dog  Spayed Female   
13        14         NaN  2015-09-22 18:17:00        Dog  Neutered Male   
14        15       Duffy  2014-07-20 19:24:00        Dog  Neutered Male   
15        16       Jiggy  2014-03-26 18:33:00        Dog  Spayed Female   
16        17     Ghengis  2015-05-29 17:04:00        Dog  Neutered Male   
17        18      Decker  2016-01-19 19:31:00        Dog  Neutered Male   
18        19    Freckles  2014-06-16 12:49:00        Cat  Spayed Female   
19        20         NaN  2014-02-11 19:27:00        Cat  Intact Female   
20        21     Pumpkin  2014-11-14 19:32:00        Cat  Spayed Female   
21        22         NaN  2015-05-04 13:46:00        Cat        Unknown   
22        23       Pluto  2014-06-07 14:14:00        Dog  Neutered Male   
23        24         NaN  2014-07-20 15:37:00        Cat  Intact Female   
24        25      Portia  2013-10-26 16:23:00        Dog  Spayed Female   
25        26         NaN  2014-12-29 13:10:00        Cat  Neutered Male   
26        27        Lucy  2015-07-23 16:18:00        Cat  Spayed Female   
27        28         NaN  2015-03-19 08:33:00        Dog    Intact Male   
28        29        Jack  2014-10-09 17:22:00        Dog  Neutered Male   
29        30      Knight  2014-05-13 17:03:00        Dog  Neutered Male   
...      ...         ...                  ...        ...            ...   
11426  11427      Fatboy  2013-12-28 14:22:00        Dog  Neutered Male   
11427  11428     Calypso  2013-12-21 15:55:00        Dog  Intact Female   
11428  11429        Bolt  2013-11-15 12:32:00        Dog  Neutered Male   
11429  11430        Mary  2014-02-17 18:04:00        Dog  Spayed Female   
11430  11431         NaN  2014-12-08 12:40:00        Cat  Spayed Female   
11431  11432         NaN  2015-06-30 09:00:00        Cat    Intact Male   
11432  11433       Fiona  2014-03-21 17:33:00        Dog  Spayed Female   
11433  11434      Evanna  2015-08-16 16:40:00        Cat  Intact Female   
11434  11435       April  2015-09-06 12:41:00        Dog  Spayed Female   
11435  11436         NaN  2015-08-13 17:09:00        Cat    Intact Male   
11436  11437         NaN  2014-03-21 17:42:00        Cat  Neutered Male   
11437  11438    Peludita  2014-01-10 13:46:00        Dog  Intact Female   
11438  11439         NaN  2015-05-02 20:40:00        Dog  Neutered Male   
11439  11440       Socks  2014-05-18 16:47:00        Dog  Spayed Female   
11440  11441         NaN  2015-10-20 17:13:00        Cat        Unknown   
11441  11442      Doogie  2015-01-07 17:41:00        Dog  Neutered Male   
11442  11443    Sterling  2015-11-28 16:23:00        Dog  Neutered Male   
11443  11444       Bella  2014-10-04 12:17:00        Cat  Spayed Female   
11444  11445         NaN  2014-06-01 17:15:00        Cat  Intact Female   
11445  11446         NaN  2015-04-14 14:34:00        Cat    Intact Male   
11446  11447         NaN  2015-07-19 20:03:00        Cat  Neutered Male   
11447  11448       Sadie  2014-10-1

In [17]:
test_transformed = []
for idx, row in test.iterrows():
    lis = []
    for key in test_keys:
        if key == "AgeuponOutcome":
            age_in_days = convertAgeToNum(row[key])
            lis.append(age_in_days)
        elif key == 'Color':
            if str(row[key]) != "nan" and str(row[key]).lower() != "unknown":
                lis.append(getColorCode(row[key]))
            else:
                lis.append(0)
        elif str(row[key]) != "nan" and str(row[key]).lower() != "unknown":
            temp = np.where(dict_temp[key] == row[key])
            if len(temp[0]) > 0:
                lis.append(temp[0][0]+1)
            else:
                lis.append(0)
        else:
            lis.append(0)
    test_transformed.append(np.array(lis))

In [18]:
test_transformed = np.array(test_transformed, np.int16)
#np.set_printoptions(threshold='nan')
print test_transformed

[[   1    4  300   19    9]
 [   1    2  730  105    6]
 [   2    1  365    2    8]
 [   1    3  120  328   28]
 [   1    1  730   67   10]
 [   1    1 1095   48    1]
 [   2    1 4745   38   33]
 [   2    2  180    2    8]
 [   1    2   90    7  119]
 [   1    2  365    3    1]
 [   1    2  150   19   17]
 [   1    4  730    3    3]
 [   1    2  180    3   37]
 [   1    1  730   67   10]
 [   1    1  365  937   19]
 [   1    2  120  110   10]
 [   1    1 1825   72    6]
 [   1    1 1095  120   75]
 [   2    2 1095    2   26]
 [   2    4 1460    2   26]
 [   2    2  730    2   11]
 [   2    0   21    2   11]
 [   1    1  365  295   22]
 [   2    4    7    2   29]
 [   1    2  365  682    5]
 [   2    1  365    2    8]
 [   2    2   60   38   90]
 [   1    3   60  295   13]
 [   1    1 1095   19   17]
 [   1    1  730   19   11]
 [   1    2 1460  217   17]
 [   1    2   60   49   17]
 [   2    1  730   38    8]
 [   2    1   60    2   33]
 [   2    4   60    2   29]
 [   1    1  365   6

In [ ]:
#train = np.array(train)
#trainSet = train[:int(train.shape[0]*0.7), :]
#valSet = train[int(train.shape[0]*0.7):,:]

#labels = np.array(labels)
#trainLabelSet = labels[:int(labels.shape[0]*0.7)]
#valLabelSet = labels[int(labels.shape[0]*0.7):]


train = np.array(train)
trainSet = train[:70, :]
valSet = train[71:100,:]

labels = np.array(labels)
trainLabelSet = labels[:70]
valLabelSet = labels[71:100]

In [ ]:
import yaml

with open("./ToolBox/params.json") as data_file:
    #params = json.loads(data_file, object_hook=ascii_encode_dict)
    params = yaml.safe_load(data_file)
    
functions = CrossValidation.init(params, trainSet, trainLabelSet, valSet, valLabelSet)

best_config = functions["svm"](decision_function_shape="ovo")

best_config

Total configurations: 18
Starting configuration: 1, params: {'kernel': 'linear', 'C': 1}
Model fit finished. Calculating accuracy.
Current setting accuracy: 0.310344827586
Current best accuracy: 0.310344827586
------ Current setting execution time: 11 seconds = 0 minutes ------
Starting configuration: 2, params: {'kernel': 'linear', 'C': 10}
Model fit finished. Calculating accuracy.
Current setting accuracy: 0.275862068966
Current best accuracy: 0.310344827586
------ Current setting execution time: 49 seconds = 0 minutes ------
Starting configuration: 3, params: {'kernel': 'linear', 'C': 100}
Model fit finished. Calculating accuracy.
Current setting accuracy: 0.275862068966
Current best accuracy: 0.310344827586
------ Current setting execution time: 246 seconds = 4 minutes ------
Starting configuration: 4, params: {'kernel': 'poly', 'C': 1, 'degree': 3}


In [ ]:
from sklearn import svm

rf = svm.SVC(decision_function_shape='ovo')
rf.fit(train, labels)

In [ ]:
np.savetxt('./submission_SVM_OVO.csv', rf.predict(test_transformed), delimiter=',', fmt='%f')

In [ ]:
res = np.loadtxt('submission_SVM_OVO.csv', delimiter=',')

lis = []
for idx, y in enumerate(res):
    temp_lis = np.zeros(6)
    temp_lis[0] = idx+1
    temp_lis[y] = 1
    lis.append(temp_lis)

np.savetxt('submission_SVM_OVO.csv', lis, fmt='%d', delimiter=',')